### ISSUE TITLE
Is there support to not walk the children by returning false, similar to react-tree-walker?

### ISSUE THREAD

**Issue by rodinhart** [FormidableLabs/react-ssr-prepass#10]

**Comment by kitten** [comment]
Sorry for the late reply. No there's currently no way to interrupt the rendering, since it didn't seem like there was a specific use-case for it. I weighed the potential minor performance gains against the possibility of accidental bugs, and I think since this repository is fully forkable, I don't want to overcomplicate things

**Comment by rodinhart** [comment]
Understood. Thank you for the reply.
