### ISSUE TITLE
Problems with actions on redirect

### ISSUE THREAD

**Issue by xmcdogx2** [FormidableLabs/react-ssr-prepass#18]
Hi.

I've faced with a problem during SSR.
I send GraphQL query on page 1 by action creator. Process response in success action creator and if some property is true I make redirect to another URL. New URL also send query, but ssrPrepass ignore redirect and second query doesn't provided to initial state and page looks incorrect.

`

    const visitor = (el, instance) => {
      if (instance && instance.fetchData) {
        return instance.fetchData()
      }
      ...
    }

    await ssrPrepass(App, visitor)
`

P.S.: I used react-tree-walker before and it worked with redirects correct.

**Comment by kitten** [comment]
I'm not quite sure I'm following this but basically, if I get this right:

1. You've got an asynchronous `fetchData` on a component that is visited
1. Then `fetchData` makes a query and you process the response and store it in some request-global / app-global state
1. You then (in the affected case) perform a redirect, presumably still on the server
1. The redirect isn't being made
1. Some kind of second query comes into play

So I'm pretty sure for the last two points I'm missing some information to be able to help you. I assume you want to abort traversal at that point? So, that's obviously something that the `react-ssr-prepass` visitor doesn't support, so let's assume traversal continues.

After `react-ssr-prepass` is done you've marked request to redirect, but are you aborting all other actions, like server-side rendering?

Usually I'd do that (in my case an express server for instance) by checking whether a redirect was scheduled using `req.headersSent`. If you're not familiar with that, if you start a redirect then it's clear that your request doesn't need any other content in the response headers than the redirect, so Express goes ahead and sends the redirect down.

So at that point you can back off in your server-side code and say:

```js
if (req.headersSent) return
// ... some React SSR code comes after
```

Now, I'm not sure what you mean by this last part:

> second query doesn't provided to initial state and page looks incorrect

But could it be that you were relying on `react-tree-walker`'s traversal cancellation, where you could stop it from traversing deeper by returning `false`?

There's a little "hack" that you can do, since you're not using suspense. You can take `instance` (the one you call `instance.fetchData` on) and change the state to tell you to abort early, e.g.:

```js
class YourComponent extends React.Component {
  fetchData = async () => {
    await yourFetchCall()
    if (...) {
      res.redirect(...) // I assume this comes from somewhere
      this.setState({ abort: true })
    }
  }

  render() {
    if (this.state.abort) {
      return null; // stop traversal for react-ssr-prepass
    }

    // ...
  }
}
```
