### ISSUE TITLE
When the page loads I see function reactDom(__x3) { return __ref2.apply(this, arguments) } ?

### ISSUE THREAD

**Issue by golubvladimir** [FormidableLabs/react-ssr-prepass#23]
When the page loads I see function reactDom(__x3) { return __ref2.apply(this, arguments) } ?
I have the latest version.

**Comment by golubvladimir** [comment]
After the page is displayed.

**Comment by golubvladimir** [comment]
server.js
`       
            jsx = extractor.collectChunks(<Provider store={ store }>
                <StaticRouter context={ context } location={ req.url }>
                    <JssProvider registry={sheets}>
                        <AppMain />
                    </JssProvider>
                </StaticRouter>
            </Provider>);

            ....
            const reactDom = async jsx => {
              const element = createElement(jsx);
              await ssrPrepass(element);

              return renderToString(element);
           };
`

**Comment by kitten** [comment]
Sounds like you’re printing the function and sending that to the client instead of an actual value.

Also please keep in mind that issues are more effective when you add more detail, so basically out-of-context code snippets, questions, missing reproductions, and similar issues can not be resolved easily, so you’re less likely to get the help you need.

For any questions like this it’s often therefore more advisable to check StackOverflow :)
