### ISSUE TITLE
what could we do while ssr-prepass and renderToNodeStream

### ISSUE THREAD

**Issue by sayjeyhi** [FormidableLabs/react-ssr-prepass#47]
There is a gap between we are waiting to `ssrPrepass(element)` finish (api calls finish) and `renderToNodeStream` which increase TTFB, is there any idea about doing sth in this gap.

for example if we could get helmet needs data and stream header before finishing the whole `ssr-prepass` promise..

**Comment by kitten** [comment]
So if you don’t have a lot of async tasks you can also try out react-lightyear: https://github.com/Ephem/react-lightyear

It only does a single render pass but comes with other caveats. It will reduce TTFB but that will only be useful depending on where your suspense boundary is.

It may be worth though for you to look into CDN caching if possible, since that’ll always have the greatest impact.

A middle ground may be to move the entire schema execution into the SSR server. That could have event loop implications as your SSR server does more work, but since you’ll execute the schema in the same process, you also have more in-memory caching options. (That depends on this package being shipped https://github.com/FormidableLabs/urql/pull/474)

So overall you have several options but they really depend more on your architecture and on finding small workarounds since this is inherently an issue with SSR :)

**Comment by sayjeyhi** [comment]
Thank you dear @kitten, actually I take a look at `react-lightyear` and give it a try, I see it is not the thing I am looking for. Specially using `throw` to handle api call suspense, gets a little bit complicated redux or saga.

I see `react-ssr-prepass` is doing better my tasks. I got an idea and it improved my TTFB, I write html head with main js and css file to be `preloaded`, it decreased my `TTFB` to 100ms. In other hand it helped me to preload my main js file parallel with prepassing SSR needs api calls.

```javascript
const statsFile = path.resolve(
    `./build/loadable-stats.json`,
);
const chunkExtractor = new ChunkExtractor({ statsFile });
const { stats } = chunkExtractor;

res.set({ 'content-type': 'text/html; charset=utf-8' });
res.write('<!doctype html><html lang="fa"><head>
<link rel="preload" href="${stats.assetsByChunkName.main}" as="script" />
<script async src="${stats.assetsByChunkName.main}" ></script>
');
```

Maybe some one asks about handling `404,301` cuz I am writing data on `response` before deciding about route existence or redirection, for that purpose I used `matchPath` from `react-router-dom` so I can predict them.
