### ISSUE TITLE
React 17 RFC and future maintenance

### ISSUE THREAD

**Issue by LucaColonnello** [FormidableLabs/react-ssr-prepass#57]
Hello 👋
First of all thanks for the great work on this library!!

I'm wanted to ask, is there any plan to support React 17, whenever it'll come out?
I suppose, what I mean is if you're going to support this library and make it compatible with newer versions of React.

Thanks a lot again, great work on this project...
🎉

**Comment by kitten** [comment]
It's very likely that this library is going to continue working without any modifications! ✨ The behaviour, element behaviour, and hooks logic hasn't changed and likely won't change. Some APIs will probably be moved into stable (likely `useMutableSource`) so that's a minor change.

Apart from that this library is planned to be maintained until React provides a similar solution on their own (namely via React Flight, I believe)

**Comment by LucaColonnello** [comment]
Amazing news!!
We like this lib a lot as we use urql with it for ssr, so we were spiking a more general purpose usage for all our ssr cases.

I was trying to make it work with react-query, which supports suspense, but I got in an infinite loop and was wondering if it was an issue with React compatibility.

Thanks for letting me know!
